# Visit https://github.com/lowlighter/metrics#-documentation for full reference

# Your GitHub token
# The following scopes are required:
#  - public_access (default scope)
# The following additional scopes may be required:
#  - read:org      (for organization related metrics)
#  - read:user     (for user related data)
#  - read:packages (for some packages related data)
#  - repo          (optional, if you want to include private repositories)

name: GitHub Profile Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # THE METRICS BASE HEADER/CONFIGS
  metrics-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ${{ github.job }}.svg

          # Options
          user: vvhybe
          template: classic
          base: header, metadata
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          config_octicon: yes
          config_twemoji: yes

  
  # THE Isometric commit calendar
  metrics-isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ${{ github.job }}.svg

          # Options
          user: vvhybe
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  
  # THE PROGRAMMING LANGUAGES LIST
  metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ${{ github.job }}.svg

          # Options
          user: vvhybe
          template: classic
          base: ""
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

  
  # THE ISSUES/PRs FOLLOW-UP ANALTICS sum(closed/opened)
  metrics-issues-followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ${{ github.job }}.svg

          # Options
          user: vvhybe
          template: classic
          base: ""
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
  

  # THE ISSUES/PRs FOLLOW-UP ANALTICS sum(closed/opened)
  metrics-achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ${{ github.job }}.svg

          # Options
          user: vvhybe
          template: classic
          base: achievements
          plugin_achievements: yes
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
